### ISSUE TITLE
Silverfin panel - auto-refresh when changing details

### ISSUE THREAD

**Issue by Woetfin** [silverfin/silverfin-vscode#14]
**Describe the bug**
When changing your default firm ID or updating the `config.json` of a template, this update is not automatically reflected in the sidebar panel. 

**To Reproduce**
1. Go to the Silverfin sidebar
2. Go to the 'Firms' section of the sidebar
3. Under 'Authorized firm IDs', your currently set default firm has an 'ACTIVE' label next to it.
4. Press CTRL + SHIFT + p to open the VS Code command panel
5. Select the command 'Silverfin: set firm ID'
6. Set a different firm ID than your current default one. 
7. If you go back to the Silverfin panel, the 'ACTIVE' label is still set on the old default firm, while on the background you already changed your default firm. 
8. This 'ACTIVE' label is only updated on a full-restart of VS Code. 

Same issue applies for any direct update done in the config.json of the template

**Expected behavior**
The information in the sidebar should always match your current configuration. 

**Desktop & CLI (please complete the following information):**
 - OS: WSL2
 - CLI version (run `silverfin --version`): 1.9.1

**Comment by AgustinSilverfin** [comment]
I think point 8 is not completely correct. The ACTIVE label is (was) updated when you switched tabs in the editor. 
Now I made an update that it (the firm section) should be reloaded after changing the default firm id using the command

Also, now every section in the sidebar should be reloaded when the file opened get's saved (as mentioned earlier, panels were only rendered when switching tabs / changing the 'active text editor'). This should address your issue with changes to `config.json`

@Woetfin you should be able to check this in `v1.8.5`
