### ISSUE TITLE
Make sure snippet "<some_tag TAB" can be used

### ISSUE THREAD

**Issue by Snakefin** [silverfin/silverfin-vscode#34]
**Describe the bug**
When using the Silverfin platform editor, we have certain snippets we can use to create elements in a HTML table. 
eg doing '<table' or '<tr' and TAB, will create the correct element. 

However, in our CLI, when doing the same, it will actually create an unneeded additional open and closing tag (< and >), this breaking the output of the HTML table. 

**To Reproduce**
1. Use '<tr' and TAB
2. Check the open and closing tags

You'll see this: 

```
      <<tr>
        <td>
          content
        </td>
      </tr>>
```

**Expected behavior**

```
<tr>
        <td>
          content
        </td>
      </tr>
```

**Screenshots or Pull request**

See https://silverfin.slack.com/archives/C0376K9NNTS/p1695196982800949

**Desktop & CLI (please complete the following information):**
 - OS: macOS (latest version)
 - CLI version (run `silverfin --version`): **1.18.2**

**Comment by Woetfin** [comment]
@Snakefin in the current extension, it's enough to just type `tr` to get the snippet instead of `<tr`, it's one character less so I don't think it's a problem? The extra `<`, is added because this isn't needed for the shortcut anymore to get the snippet
![Screenshot 2023-10-04 at 13 25 49](https://github.com/silverfin/silverfin-vscode/assets/99254741/fd2b5a25-89b5-43c2-bce5-2338e43eb471)

**Comment by Snakefin** [comment]
It's not a problem per sé, but it does break habits of people that are used to our platform editor though. Hence the issue here, as I was expecting all snippets of our platform editor to behave exactly the same in our CLI 😅 

Matter of getting used to it, not a biggie ☺️

**Comment by Woetfin** [comment]
@Snakefin are you used to it already and I can close this? 😄

**Comment by Snakefin** [comment]
I am indeed used to it by now; clever on your part waiting 😉

**Comment by Woetfin** [comment]
Patience is a virtue 😇
