### ISSUE TITLE
Add new snippets

### ISSUE THREAD

**Issue by Woetfin** [silverfin/silverfin-vscode#5]
# Add new snippets

This thread can be used to mention any snippets that you would like to see added to the VS Code extension. 

## Snippets confirmed to be added 

| shortcut  | description  | snippet
|----------- |--------------| ----------
| when       |Add a when-tag that is used within case-tags | `{% when "" %}`
| newpage | Add a newpage tag to signify the start of a new page |  `{% newpage %}`    
| currencyconfiguration | Add opening and closing currencyconfiguration-tags with the possible attributes | `{% currencyconfiguration negative_format:"-xxx" zero_format:"0" precision:3 delimiter:" " separator:"," %}content{% endcurrencyconfiguration %}`
| endcurrencyconfiguration | Only add closing currencyconfiguration-tag | `{% endcurrencyconfiguration %}`
| int | add the INT type conversion function | `INT(content)`
| max | add the MAX function to return the largest value in an array of values | `MAX(value_1;value_2)`
| min | add the MIN function to return the smallest value in an array of values | `MIN(value_1;value_2)`
| localized | add the localized filter | `localized`
| localize: | add the localize attribute | `localize:true`
| date:"%d/%m/%Y" | add the filter for standard BE date formatting (DD/MM/YYYY) | `date:"%d/%m/%Y"`
| date:"%F" |  add the filter for ISO date formatting (YYYY-MM-DD) | `date:"%F"`

## Add snippets for general drops
For each method of the CompanyDrop we will add snippets so developers get a proposal of all possible methods on a drop when they're typing. 

Some examples:

| shortcut  | description  | snippet
|----------- |--------------| ----------
| company.name | access the company name of the current company | company.name
| company.vat_identifier | access the company number of the current company | company.vat_identifier
| company.company_type | access the company form / legal form of the current company | company.company_type
| ... | ... | ...

Add this for each method of the [CompanyDrop](https://developer.silverfin.com/docs/company), the [PeriodDrop](https://developer.silverfin.com/docs/period), the [AccountsDrop](https://developer.silverfin.com/docs/accounts), the [ReconciliationsDrop](https://developer.silverfin.com/docs/reconciliations), the [PeopleDrop](https://developer.silverfin.com/docs/people) and the [UserDrop](https://developer.silverfin.com/docs/user)

**Comment by Snakefin** [comment]
Also @Toby-Masters-SF , can you make sure the focus of an include tag, is on the second part of the code (instead of the first)? 

See https://silverfin.slack.com/archives/C0376K9NNTS/p1699267659006959

**Comment by robindeclercq** [comment]
Also include this one please 🙏 
https://silverfin.slack.com/archives/C01KFA05WPM/p1706878379603819

**Comment by Woetfin** [comment]
Also go through any other snippets-related tickets in the "Issues":
* https://github.com/silverfin/silverfin-vscode/issues/53
* https://github.com/silverfin/silverfin-vscode/issues/62
* https://github.com/silverfin/silverfin-vscode/issues/60
* https://github.com/silverfin/silverfin-vscode/issues/61
* https://github.com/silverfin/silverfin-vscode/issues/34
* https://github.com/silverfin/silverfin-cli/issues/108
* https://github.com/silverfin/silverfin-cli/issues/107
* https://github.com/silverfin/silverfin-cli/issues/103
* https://github.com/silverfin/silverfin-cli/issues/102
